apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  namespace: inv2
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: inv2.loc
      http:
        paths:
          - pathType: Prefix
            path: /api/v2/auth/?(.*)
            backend:
              service:
                name: auth-srv
                port:
                  number: 3001
          - pathType: Prefix
            path: /api/v2/users/?(.*)
            backend:
              service:
                name: auth-srv
                port:
                  number: 3001
          - pathType: Prefix
            path: /api/v2/logs/?(.*)
            backend:
              service:
                name: logs-srv
                port:
                  number: 3100