apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-lms
  namespace: inv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
        - name: lms
          # image: inv2registry.azurecr.io/demo/lms
          image: integrationschd/inv2-lms
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BACKEND_BASE
              valueFrom:
                secretKeyRef:
                  name: common.depl
                  key: BACKEND_BASE
---
apiVersion: v1
kind: Service
metadata:
  name: lms-srv
  namespace: inv2
spec:
  selector:
    app: lms
  ports:
    - name: lms
      protocol: TCP
      port: 3001
      targetPort: 3001
