name: Deploy Auth-Staging To DigitalOceans

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: Create Pem file and connect to 
        run: |
          mkdir -p ~/.ssh/
          echo "$AWS_SSH_KEY" > ../private.pem
          sudo chmod 600 ../private.key
      - run: ssh -i $AWS_SSH_KEY ec2-user@bastation-chd.zanibal.com
        env:
          DOCKER_USERNAME: ${{ secrets.AWS_SSH_KEY }}
      - run: kubectl rollout restart deployment invest -n invest