name: Deploy InvestIN-Staging To DigitalOceans

on:
  push:
    branches:
      - 'staging'
    paths:
      - 'Backend/InvestIN/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - run: cd Backend/InvestIN && docker build -t integrationschd/inv2-investin .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push integrationschd/inv2-investin
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save inv2
      - run: kubectl rollout restart deployment depl-investin -n inv2