name: Deploy Auth-Master To AWS

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Create Pem file and connect to Prod
        run: |
          mkdir -p ~/.ssh && touch private.pem
          echo $AWS_SSH_KEY > ~/.ssh/private.pem
          cat ~/.ssh/private.pem
        shell: bash
        env:
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
