name: Deploy Auth-Master To AWS

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pem file and connect to Prod
        uses: appleboy/ssh-action@master
        with:
          host: bastation-chd.zanibal.com
          key: ${{ secrets.AWS_SSH_KEY }}
          username: ec2-user
          script: |
            kubectl rollout restart deployment invest -n invest
