name: Deploy WebClient-Staging To DigitalOceans

on:
  push:
    branches:
      - 'staging'
    paths:
      - 'Frontend/web/client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - run: cd Frontend/web/client && docker build -t integrationschd/inv2-web-client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push integrationschd/inv2-web-client
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: staging
    steps:
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save inv2
      - run: kubectl rollout restart deployment depl-web-client -n inv2