name: Test LMS

on:
  pull_request:
    paths:
      - 'Backend/LMS/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - run: cd Backend/LMS && npm install && npm run test:ci
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}