name: Test Auth

on:
  pull_request:
    paths:
      - 'Backend/Auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - run: cd Backend/Auth && npm install && npm run test:ci
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          AES_SECRET_KEY: ${{secrets.AES_SECRET_KEY}}
          ACCESS_TOKEN_TIME: ${{secrets.ACCESS_TOKEN_TIME}}
          BACKEND_BASE: ${{secrets.BACKEND_BASE}}